GET http://localhost:5000/users

###

GET  http://localhost:5000/users/66825a0c873253329459fad8

###

PATCH  http://localhost:5000/users/668622a9bf838fae12ccdb16
Content-Type: application/json

{
    "name":"ambatukam",
    "email":"yandexsczczcc",
    "gender":"male"
}

###

DELETE http://localhost:5000/users/66825a0c873253329459fad8

###

GET http://localhost:5000/pesan


###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name":"new",
    "email":"askdjkajdskjasd",
    "gender":"female"
}

###
POST http://localhost:5000/home
Content-Type: application/json

{
    "text":"Casa Evaliza is a spacious Bali rental villa, located 250 metres from the beach in the up market Seminyak area on Bali's southwest coast and accessed through the same road which serves the Club at The Legian Hotel, and just minutes walk from the world famous Ku De Ta restaurant."
}

###
GET http://localhost:5000/home

###

DELETE http://localhost:5000/home/668e76e55d33d52483203083