# USER
GET http://localhost:5000/users
###
GET  http://localhost:5000/users/66825a0c873253329459fad8
###
PATCH  http://localhost:5000/users/668622a9bf838fae12ccdb16
Content-Type: application/json

{
    "name":"ambatukam",
    "email":"yandexsczczcc",
    "gender":"male"
}
###
POST  http://localhost:5000/users
Content-Type: application/json
{
    "name":"new",
    "email":"askdjkajdskjasd",
    "gender":"female"
}
###
DELETE http://localhost:5000/users/66825a0c873253329459fad8

# PESAN
###
GET http://localhost:5000/pesan

# HOME
###
